name: kirkstone-arm-128.8.0esr
run-name: Build ESR Firefox for 32-bit ARM architecture with Kirkstone
on:
  pull_request:
    branches:
      - master
    paths:
      - 'meta-firefox/**'

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build-kirkstone-arm-esr:
    runs-on: [self-hosted, desktop]
    container:
      image: skandigraun/yocto:latest
      volumes:
        - yocto:/yocto
    environment: ff-build-env
    steps:
      - run: |
         mkdir -p /yocto/kirkstone
         cd /yocto/kirkstone
         rm -rf meta-browser meta-firefox-test
         git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
         git -C meta-browser checkout $GITHUB_HEAD_REF
         # clone the test repo
         git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY_OWNER/meta-firefox-test
         ./meta-firefox-test/scripts/build.sh kirkstone arm esr
  test-kirkstone-arm-esr:
    runs-on: [self-hosted, desktop]
    needs: build-kirkstone-arm-esr
    steps:
      - run: |
         cd /yocto/kirkstone
         ./meta-firefox-test/scripts/test.sh kirkstone arm esr
      - uses: dorny/test-reporter@v1
        if: always()
        with:
          path: meta-firefox/test-results/*.xml
          reporter: java-junit
          name: Test Results - kirkstone arm ESR
          working-directory: /yocto/kirkstone/meta-browser
